### PR TITLE
Port Zephyr non rpi5 patches to  zephyr-v3.6.0-xt

### PR DESCRIPTION
**Pull request by GrygiriiS**
Port Zephyr non-RPI5 specific patches to  zephyr-v3.6.0-xt with intention to switch of from rpi5_dev branch.

Only one HACK is left, but now there is no way to get rid of it for dom0less support, last upstream series [1].

[1] https://patchew.org/Xen/20240511005611.83125-1-xin.wang2@amd.com/

### CODE REVIEW

**Review by firscity — APPROVED** [review]
I think it is better to remove `HACK: ` from third commit, it is not actually hack

`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by GrygiriiS** [comment]
> I think it is better to remove `HACK: ` from third commit, it is not actually hack
> 

I'd prefer to keep it to emphasize that it's not stable solution and we need to track xen mainline process for this.

**Comment by firscity** [comment]
> I'd prefer to keep it to emphasize that it's not stable solution and we need to track xen mainline process for this.

It is still not a "hack". I'd prefer to not have patches with such marks in commit topic in main development branch, you've already mentioned this in commit description

**Comment by firscity** [comment]
You can add AB for third commit and I will merge this PR.

**Pull request merged**
