### PR TITLE
drivers: serial: add support of hscif driver for RCar boards

### PR DESCRIPTION
**Pull request by lorc**
Add support of HSCIF UART driver for Renesas boards.

---

This is backport from mainline Zephyr.

### CODE REVIEW

**Review by xakep-amatop — APPROVED** [review]
It is also necessary to add a node of HSCIF, as has been done in the mainline:
https://github.com/zephyrproject-rtos/zephyr/blob/main/dts/arm64/renesas/r8a779f0.dtsi#L110
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/renesas/rcar_spider_s4/rcar_spider_s4_r8a779f0_a55-pinctrl.dtsi#L10
https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/renesas/rcar_spider_s4/rcar_spider_s4_r8a779f0_a55.dts#L27

**Comment by lorc** [comment]
Interestingly, HSCIF nodes are already present:

https://github.com/xen-troops/zephyr/blob/zephyr-v3.6.0-xt/boards/arm64/rcar_spider_ca55/rcar_spider_ca55.dts#L32

All I had to do is port this one patch.

**Comment by xakep-amatop** [comment]
> Interestingly, HSCIF nodes are already present:
> 
> https://github.com/xen-troops/zephyr/blob/zephyr-v3.6.0-xt/boards/arm64/rcar_spider_ca55/rcar_spider_ca55.dts#L32
> 
> All I had to do is port this one patch.

My apologies, I've checked the `zephyr-v3.3.0-xt` branch for these changes instead of `zephyr-v3.6.0-xt`.

**Comment by GrygiriiS** [comment]
Please, add explicit note in commit message that it's back port:` ("cherry-pick -x") or smth. like "[commit <hash> upstream]". `

**Comment by lorc** [comment]
Updated the commit message

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by GrygiriiS** [comment]
> Updated the commit message

Thank you, nut note, commit SHA should be 12 digit/chars

**Comment by lorc** [comment]
> Thank you, nut note, commit SHA should be 12 digit/chars

Are you sure? As I can see, Linux kernel developers always us full SHA1 hash. Also, please note that GitHub mangles commit messages. In this case it replaced full SHA1 hash with shortened one and made it a hyperlink.

**Comment by GrygiriiS** [comment]
> > Thank you, nut note, commit SHA should be 12 digit/chars
> 
> Are you sure? As I can see, Linux kernel developers always us full SHA1 hash. Also, please note that GitHub mangles commit messages. In this case it replaced full SHA1 hash with shortened one and made it a hyperlink.

12 is min. I've no objections to this PR, especially considering your comment  about github behavior. I can't add my tag here as I'm not familiar with HW.

**Comment by lorc** [comment]
>  I've no objections to this PR, especially considering your comment about github behavior

Yeah, you can check the raw commit by adding ".patch" to the patch URL

https://github.com/xen-troops/zephyr/commit/5119451f3437a4d606a402a707c72f9d5f016352.patch

**Pull request merged**
