### PR TITLE
drivers: gpio_rcar: add memory mapping to driver

### PR DESCRIPTION
**Pull request by xakep-amatop**
Add memory mapping to driver in order to use driver with platforms based on Cortex A with enabled MMU.

### CODE REVIEW

**Comment by xakep-amatop** [comment]
the same changes have been already merged to zephyr mainline and will be available after 3.4 release

**Review by firscity — APPROVED** [review]
Please, mention that these changes will be present in 3.4 mainline Zephyr and should be dropped during migration

With this: `Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by lorc** [comment]
If you are backporting code from mainline, there is no need to review it locally. Just mention in the commit message that this is a backport. This mostly done by adding something like this: `[backported from v3.4]` into the tags section. You can check git commit logs for more examples.

**Comment by xakep-amatop** [comment]
add the tag to the commit message

**Comment by xakep-amatop** [comment]
> If you are backporting code from mainline, there is no need to review it locally. Just mention in the commit message that this is a backport. This mostly done by adding something like this: `[backported from v3.4]` into the tags section. You can check git commit logs for more examples.

so is it not needed to add acked-by or reviewed-by lines to commit message?

**Comment by lorc** [comment]
> so is it not needed to add acked-by or reviewed-by lines to commit message?

In my opinion - no. But could you please put `[backported from v3.4]` into the right place?

**Comment by xakep-amatop** [comment]
> > so is it not needed to add acked-by or reviewed-by lines to commit message?
> 
> In my opinion - no. But could you please put `[backported from v3.4]` into the right place?

done

**Comment by lorc** [comment]
Thanks. I believe we can merge this.
@firscity ?

**Pull request merged**
