### PR TITLE
Port Zephyr RPI5 patches to zephyr-v3.6.0-xt

### PR DESCRIPTION
**Pull request by GrygiriiS**
Depends on https://github.com/xen-troops/zephyr/pull/110

Port Zephyr RPI5 specific patches to zephyr-v3.6.0-xt with intention to switch of from rpi5_dev branch.

Below Hack is still here for testing purposes:
[HACK: TMP: xen: public: domctl: tmp adjust version](https://github.com/xen-troops/zephyr/commit/f3e9f6eb81608b80f27fe598e61b539856cce991)

Depends on https://github.com/xen-troops/zephyr/pull/116 to get rid of above HACK
UPD: hence PR #116 was merged the above HACK is removed. BUT Zephyr application should be set to CONFIG_XEN_DOMCTL_INTERFACE_VERSION=0x16 to be compatible with xen-troops/xen-4.19-xt0.1

### CODE REVIEW

**Comment by oleksiimoisieiev** [comment]
IIUC previous implementation was based on zephyr-v3.3.0. I think it will be great to move the next rpi5 Relese to zephyr-v3.6.0
Could you please add here some test scenarios you've done? @firscity is zephyr-v3.6.0-xt ready to be based on? or it still requires some tune ups?

**Comment by GrygiriiS** [comment]
> IIUC previous implementation was based on zephyr-v3.3.0. I think it will be great to move the next rpi5 Relese to zephyr-v3.6.0 

Not sure what do you mean by "v3.3.0" :(?
 git log --oneline --graph --color xt_zephyr/rpi5_dev  | grep v3.6
* 468eb56cf242 release: Zephyr v3.6.0

**Comment by oleksiimoisieiev** [comment]
Sry. Misunderstood the point of this pr. Thought it's based on zephyr-v3.3.0-xt. 
In any case I'm happy with this changes:
`Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Comment by GrygiriiS** [comment]
updated:

- ported new patches
- removed XEN API HACK

hence PR #116 was merged the above HACK is removed. BUT Zephyr application should be set to CONFIG_XEN_DOMCTL_INTERFACE_VERSION=0x16 to be compatible with xen-troops/xen-4.19-xt0.1 


Note. All patches are ported from rpi5_dev without changes, so they are reviewed and have all tags already.

**Comment by oleksiimoisieiev** [comment]
As far as patches are already reviewed - then my Ack can be left. Also, when this will be merged I think we will probably have to make another release with both renesas and rpi5 support. After some testing for sure.

**Comment by GrygiriiS** [comment]
@mlohvynenko AOS team tried this branch with as and seen no diff with rpi5_dev

**Review by firscity — COMMENTED** [review]
one last question: did you test resulting zephyr-v3.6.0-xt with already supported HW? E.g. AoS on S4 (with lowering DOMCTL interface to 0x16)

**Comment by GrygiriiS** [comment]
No. But there is absolutely no changes which could affect them, no?

**Comment by firscity** [comment]
It touches common code, AoS on Gen3/Gen4 also uses eMMC, I am just curios if it can affect its functionality.

**Comment by GrygiriiS** [comment]
> It touches common code, AoS on Gen3/Gen4 also uses eMMC, I am just curios if it can affect its functionality.

SDHC common is generic SDH controller implementation which is NOT compatible with GenX and so not used there.
Sorry, but I fail to see what code can affect GenX or other Renesas platform. Could you point on any?

**Review by firscity — APPROVED** [review]
> which is NOT compatible with GenX and so not used there

OK, I see.

**Pull request merged**
