### PR TITLE
drivers: optee: Remove warning message

### PR DESCRIPTION
**Pull request by dsemenets**
Remove obsolete warning message.

### CODE REVIEW

**Comment by oleksiimoisieiev** [comment]
lgtm `Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Comment by lorc** [comment]
Could you please clarify why it is obsolete? E.g. could you provide reference to a commit that fixed this?

**Comment by dsemenets** [comment]
> Could you please clarify why it is obsolete? E.g. could you provide reference to a commit that fixed this?

Message was "Memref param are not fully tested". During tests we didn't see any issues with memrefs.

**Comment by lorc** [comment]
`Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Pull request merged**
