### PR TITLE
Rcar mmc restore mmc after reset

### PR DESCRIPTION
**Pull request by xakep-amatop**

### CODE REVIEW

**Comment by lorc** [comment]
This is very strange pull request. You are adding some functionality, but you are not describing why do you need this in the first place. Could you please write a proper commit descripion?

Also, why are you removing `MMC_INIT_SD_CLK_DIV_SHIFT`?

**Comment by xakep-amatop** [comment]
> This is very strange pull request. You are adding some functionality, but you are not describing why do you need this in the first place. Could you please write a proper commit descripion?
> 
> Also, why are you removing `MMC_INIT_SD_CLK_DIV_SHIFT`?

done

**Review by lorc — COMMENTED** [review]
s/resoring/restoring/ in the commit message. 

"does not necessarily reset I/O settings to boot" - are you using "to boot" in sense "as well" there?'

With commit msg fixed:

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by xakep-amatop** [comment]
> "does not necessarily reset I/O settings to boot" - are you using "to boot" in sense "as well" there?'

"to boot" here is meant a state as after power cycle

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by lorc** [comment]
> > "does not necessarily reset I/O settings to boot" - are you using "to boot" in sense "as well" there?'
> 
> "to boot" here is meant a state as after power cycle

In this case you need to write "to the boot state". Because "to boot" has not the meaning you expected :)

**Comment by xakep-amatop** [comment]
> > > "does not necessarily reset I/O settings to boot" - are you using "to boot" in sense "as well" there?'
> > 
> > 
> > "to boot" here is meant a state as after power cycle
> 
> In this case you need to write "to the boot state". Because "to boot" has not the meaning you expected :)

done

**Pull request merged**
