### PR TITLE
fixup! boards: arm64: add support of Renesas Spider board

### PR DESCRIPTION
**Pull request by xakep-amatop**
Fix documentation build error:
"doc/rcar_spider.rst:document isn't included in any toctree"

### CODE REVIEW

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by xakep-amatop** [comment]
added ack tag

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by xakep-amatop** [comment]
added ack tag
@firscity pls, merge if it is possible

**Pull request merged**
