### PR TITLE
dts: r8a779f: add bus clock dev to mmc node

### PR DESCRIPTION
**Pull request by xakep-amatop**
Add bus clock device to MMC node.

### CODE REVIEW

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by xakep-amatop** [comment]
added ack
+ tested changes --- everything ok

**Review by firscity — APPROVED** [review]
Please extend commit message description
With comment fixed: 
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by xakep-amatop** [comment]
> Please extend commit message description With comment fixed: `Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

done

**Pull request merged**
