### PR TITLE
Fixes for sd card support

### PR DESCRIPTION
**Pull request by xakep-amatop**

### CODE REVIEW

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by xakep-amatop** [comment]
added ack tag to commit

**Comment by lorc** [comment]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by xakep-amatop** [comment]
added ack tag to commits
@firscity pls, merge this pr if it is possible

**Pull request merged**
